export default{
  data () {
    return {
      man_select: 'shusheng.png',
      woman_select: 'nvhai.png',
      manicons: [
        {
          id:'shusheng.png',
          name:'书生'
        },{
          id:'xizhuangnan.png',
          name:'西装男'
        },{
          id:'shibing.png',
          name:'军人'
        },{
          id:'shuaige.png',
          name:'帅哥'
        },
        {
          id:'qingdi.png',
          name:'清帝'
        },
        {
          id:'mingdi.png',
          name:'明帝'
        },
        {
          id:'qibing.png',
          name:'骑兵'
        },
        {
          id:'huangdi.png',
          name:'皇帝'
        },
        {
          id:'huajinan.png',
          name:'滑稽男'
        },
        {
          id:'shaomin.png',
          name:'少民'
        },{
          id:'llj.png',
          name:'现代男'
        },{
          id:'square.png',
          name:'方'
        }
      ],
      womanicons:[
        {
          id:'nvhai.png',
          name:'女孩'
        },{
          id:'nvbing.png',
          name:'女兵'
        },{
          id:'shunv.png',
          name:'淑女'
        },{
          id:'menggumei.png',
          name:'蒙古妹'
        },{
          id:'gege.png',
          name:'格格'
        },{
          id:'hanshi.png',
          name:'韩国美女'
        },{
          id:'zhixing.png',
          name:'知性美女'
        },{
          id:'girlfriend.png',
          name:'女友'
        },{
          id:'huanghou.png',
          name:'皇后'
        },{
          id:'huajinv.png',
          name:'滑稽女'
        },{
          id:'qipao.png',
          name:'旗袍女'
        },{
          id:'weijiu.png',
          name:'日系美女'
        },{
          id:'meinv2.png',
          name:'美女回眸'
        },{
          id:'circle.png',
          name:'圆'
        }
      ]
    }
  }
}
